SET PATH=C:\Keil_v5\ARM\ARMCC\Bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\; C:\Program Files\Java\jdk-12.0.1\bin;C:\Program Files\Java\jdk-12.0.1\jre\bin;D:\360WiFi\Git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;
SET CPU_TYPE=STM32F103RB
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Project
SET CPU_CLOCK=0x007A1200
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\main._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\main.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_it._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_it.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\misc._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\misc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_adc._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_adc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_bkp._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_bkp.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_can._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_can.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_cec._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_cec.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_crc._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_crc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "listing\stm32f10x_dac._ip"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\output\stm32f10x_dac.__i"
